#!/bin/bash
APP="$1"; IMAGE="dokku/$APP"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
set -e
echo "-----> Injecting Node ..."
NODE_VERSION=$(< "$DIR/node_version")
FILE_NAME="node-$NODE_VERSION-linux-x64"
NODE_URL="http://nodejs.org/dist/$NODE_VERSION/$FILE_NAME.tar.gz"
PACKAGES=$(cat "$DIR/packages" | tr "\\n" " ")
COMMAND=$(cat <<EOF
cd /tmp &&
wget $NODE_URL &&
tar -xf $FILE_NAME.tar.gz &&
rm -rf $FILE_NAME.tar.gz &&
cd $FILE_NAME &&
cp -rf bin/* /usr/local/bin/ &&
cp -rf share/* /usr/local/share/ &&
cp -rf lib/* /usr/local/lib/ &&
npm install -g $PACKAGES
rm -rf /temp/$FILE_NAME
EOF
)
id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Injected Node with packages: $PACKAGES"
